In [1]:
import pandas as pd

In [2]:
DATA_FILE = "input_data.csv"

In [6]:
df = pd.read_csv(DATA_FILE, sep=",", engine="python")
df = df.dropna()
df.head()

,study_area,id,Latitude,Longitude,orbit,incidence_angle,field_id,date,soil_moisture,G_VH_dB,...,Surface_r_ILSF9_BI1000,Volume_g_ILSF9_BI1000,Ratio_b_ILSF9_BI1000,projectedLocalIncidenceAngle_OLD,soil_complex,soil_type,soil_texture,top_texture,range_clay_content,assumed_clay_content
0,KEDZIERZYN,KG01,50.323410,18.129482,A175,36.95,KG,12.10.2024,17.80,-18.92,...,-15.302,-17.034,1.732,36.63,8,F,bc,mady bardzo ciężkie,pow. 50,50.0
1,KEDZIERZYN,KG02,50.323691,18.129680,A175,36.95,KG,12.10.2024,18.26,-18.41,...,-15.678,-16.317,0.639,37.37,8,F,bc,mady bardzo ciężkie,pow. 50,50.0
2,KEDZIERZYN,KG03,50.323996,18.129890,A175,36.95,KG,12.10.2024,24.14,-18.74,...,-14.058,-16.169,2.111,37.41,8,F,bc,mady bardzo ciężkie,pow. 50,50.0
3,KEDZIERZYN,KG04,50.323856,18.130370,A175,36.95,KG,12.10.2024,19.57,-18.05,...,-14.180,-16.217,2.037,36.33,8,F,bc,mady bardzo ciężkie,pow. 50,50.0
4,KEDZIERZYN,KG05,50.323531,18.130193,A175,36.95,KG,12.10.2024,20.67,-19.09,...,-16.659,-16.214,-0.445,37.04,8,F,bc,mady bardzo ciężkie,pow. 50,50.0

In [9]:
df["field_id"].value_counts()

field_id
OR     49
BGE    40
OL     30
ON     30
OE     24
       ..
KKL     2
KZ      1
JB      1
BO      1
BZ      1
Name: count, Length: 92, dtype: int64

In [14]:
df["id"].value_counts().head(50)

id
OR14     5
OR13     5
BGE06    4
BGE05    4
BGE01    4
BGE02    4
OR01     4
OR05     4
OR04     4
OR03     4
BGE07    4
OR02     4
BGE03    4
OR11     4
BGE08    4
BGE09    4
OT01     4
BGE04    4
BGE10    4
OT06     3
OZ19     3
OT03     3
OT05     3
OT02     3
OR12     3
OE12     2
OE03     2
OJ03     2
OZ10     2
OL21     2
OZ12     2
OL19     2
OR06     2
OR07     2
OI03     2
OI04     2
OL13     2
OL14     2
OL15     2
BGI05    2
BGI06    2
OZ11     2
OZ13     2
OL20     2
OL18     2
OE02     2
OE01     2
OJ01     2
OZ14     2
OZ15     2
Name: count, dtype: int64

In [17]:
df[df["id"] == "BGE06"]

,study_area,id,Latitude,Longitude,orbit,incidence_angle,field_id,date,soil_moisture,G_VH_dB,...,Surface_r_ILSF9_BI1000,Volume_g_ILSF9_BI1000,Ratio_b_ILSF9_BI1000,projectedLocalIncidenceAngle_OLD,soil_complex,soil_type,soil_texture,top_texture,range_clay_content,assumed_clay_content
754,BRWINOW,BGE06,52.145608,20.699,A029,32.56,BGE,21.03.2025,13.96,-26.29,...,-18.190,-18.607,0.418,32.599,6,Dz,ps:gs,piaski słabogliniaste,5 - 10,7.5
755,BRWINOW,BGE06,52.145608,20.699,A029,32.56,BGE,21.03.2025,13.96,-26.29,...,-18.190,-18.607,0.418,32.599,6,Dz,ps:gs,piaski słabogliniaste,5 - 10,7.5
756,BRWINOW,BGE06,52.145608,20.699,A102,41.14,BGE,25.03.2025,16.19,-21.53,...,-13.236,-18.567,5.331,41.234,6,Dz,ps:gs,piaski słabogliniaste,5 - 10,7.5
757,BRWINOW,BGE06,52.145608,20.699,A102,41.14,BGE,25.03.2025,16.19,-21.53,...,-13.236,-18.567,5.331,41.234,6,Dz,ps:gs,piaski słabogliniaste,5 - 10,7.5

In [12]:
df[df["field_id"] == "OL"]

,study_area,id,Latitude,Longitude,orbit,incidence_angle,field_id,date,soil_moisture,G_VH_dB,...,Surface_r_ILSF9_BI1000,Volume_g_ILSF9_BI1000,Ratio_b_ILSF9_BI1000,projectedLocalIncidenceAngle_OLD,soil_complex,soil_type,soil_texture,top_texture,range_clay_content,assumed_clay_content
330,OBORY,OL16,52.080624,21.169103,A029,34.55,OL,27.08.2024,17.42,-22.28,...,-15.102,-19.210,4.108,33.48,2,F,pgmp.płz,piaski gliniaste mocne,15 - 20,17.5
331,OBORY,OL16,52.080624,21.169103,A102,42.91,OL,01.09.2024,16.28,-23.68,...,-20.560,-20.654,0.093,42.94,2,F,pgmp.płz,piaski gliniaste mocne,15 - 20,17.5
332,OBORY,OL17,52.081433,21.169106,A029,34.55,OL,27.08.2024,21.23,-25.56,...,-17.462,-18.314,0.853,34.57,2,F,pgmp.płz,piaski gliniaste mocne,15 - 20,17.5
333,OBORY,OL17,52.081433,21.169106,A102,42.91,OL,01.09.2024,16.75,-23.55,...,-18.287,-20.385,2.098,42.92,2,F,pgmp.płz,piaski gliniaste mocne,15 - 20,17.5
407,OBORY,OL07,52.083602,21.160942,A029,34.55,OL,27.08.2024,36.52,-20.95,...,-20.583,-16.096,-4.487,36.80,2,zF,płz,pyły zwykłe,0 - 35,17.5
408,OBORY,OL07,52.083602,21.160942,A102,42.91,OL,01.09.2024,27.88,-23.23,...,-21.834,-19.110,-2.725,45.10,2,zF,płz,pyły zwykłe,0 - 35,17.5
409,OBORY,OL08,52.083872,21.160797,A029,34.55,OL,27.08.2024,29.09,-21.37,...,-19.691,-16.105,-3.586,34.12,2,zF,płz,pyły zwykłe,0 - 35,17.5
410,OBORY,OL08,52.083872,21.160797,A102,42.91,OL,01.09.2024,21.05,-23.15,...,-20.181,-19.700,-0.480,42.25,2,zF,płz,pyły zwykłe,0 - 35,17.5
411,OBORY,OL09,52.084501,21.160945,A029,34.55,OL,27.08.2024,33.34,-24.91,...,-17.742,-17.891,0.149,30.98,2,zF,płz,pyły zwykłe,0 - 35,17.5
412,OBORY,OL09,52.084501,21.160945,A102,42.91,OL,01.09.2024,21.22,-24.94,...,-19.505,-20.717,1.212,39.39,2,zF,płz,pyły zwykłe,0 - 35,17.5
413,OBORY,OL10,52.084319,21.162404,A029,34.55,OL,27.08.2024,32.38,-23.76,...,-20.971,-17.458,-3.513,34.25,2,zF,płz,pyły zwykłe,0 - 35,17.5
414,OBORY,OL10,52.084319,21.162404,A102,42.91,OL,01.09.2024,26.11,-25.07,...,-19.574,-20.454,0.879,42.62,2,zF,płz,pyły zwykłe,0 - 35,17.5
415,OBORY,OL11,52.084050,21.161819,A029,34.55,OL,27.08.2024,29.27,-22.28,...,-19.230,-17.753,-1.476,34.59,2,zF,płz,pyły zwykłe,0 - 35,17.5
416,OBORY,OL11,52.084050,21.161819,A102,42.91,OL,01.09.2024,27.31,-24.70,...,-19.403,-20.571,1.168,42.91,2,zF,płz,pyły zwykłe,0 - 35,17.5
417,OBORY,OL12,52.083781,21.161672,A029,34.55,OL,27.08.2024,28.13,-23.10,...,-19.945,-17.296,-2.649,33.50,2,zF,płz,pyły zwykłe,0 - 35,17.5
418,OBORY,OL12,52.083781,21.161672,A102,42.91,OL,01.09.2024,26.03,-25.38,...,-18.533,-20.140,1.606,42.02,2,zF,płz,pyły zwykłe,0 - 35,17.5
694,OBORY,OL13,52.080173,21.169539,A029,34.55,OL,27.08.2024,15.26,-22.62,...,-16.047,-17.550,1.503,34.71,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
695,OBORY,OL13,52.080173,21.169539,A102,42.91,OL,01.09.2024,13.54,-23.70,...,-21.736,-20.156,-1.581,43.05,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
696,OBORY,OL14,52.080443,21.169686,A029,34.55,OL,27.08.2024,15.78,-22.12,...,-16.811,-17.618,0.807,33.72,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
697,OBORY,OL14,52.080443,21.169686,A102,42.91,OL,01.09.2024,12.49,-24.49,...,-20.705,-21.662,0.957,42.08,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
698,OBORY,OL15,52.080713,21.169687,A029,34.55,OL,27.08.2024,19.43,-22.16,...,-18.649,-17.467,-1.182,34.01,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
699,OBORY,OL15,52.080713,21.169687,A102,42.91,OL,01.09.2024,14.94,-23.93,...,-19.321,-22.813,3.491,42.19,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
700,OBORY,OL18,52.080981,21.170418,A029,34.55,OL,27.08.2024,15.21,-21.23,...,-20.683,-16.797,-3.886,37.58,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
701,OBORY,OL18,52.080981,21.170418,A102,42.91,OL,01.09.2024,13.64,-23.18,...,-18.016,-20.613,2.598,45.91,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
702,OBORY,OL19,52.080532,21.170270,A029,34.55,OL,27.08.2024,17.17,-23.04,...,-19.305,-17.748,-1.556,34.42,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
703,OBORY,OL19,52.080532,21.170270,A102,42.91,OL,01.09.2024,14.18,-24.46,...,-19.352,-22.066,2.714,42.70,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
704,OBORY,OL20,52.080352,21.170707,A029,34.55,OL,27.08.2024,15.70,-23.30,...,-19.744,-17.683,-2.061,34.63,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
705,OBORY,OL20,52.080352,21.170707,A102,42.91,OL,01.09.2024,12.91,-24.02,...,-19.810,-20.146,0.336,42.94,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
706,OBORY,OL21,52.080172,21.170561,A029,34.55,OL,27.08.2024,18.56,-22.86,...,-19.799,-17.490,-2.310,33.63,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5
707,OBORY,OL21,52.080172,21.170561,A102,42.91,OL,01.09.2024,14.29,-24.24,...,-24.427,-19.471,-4.956,42.13,5,F,ps:gc,piaski słabogliniaste,5 - 10,7.5